In [104]:
############################################
##### L03.1 Linear Regression Practice #####
############################################

In [105]:
import torch

In [106]:
x = torch.tensor([[1,2,3], [4,5,6], [7,8,9]], dtype=torch.int)

# tensor의 모양 알아보기

print("x = ", x)
print("Type : ", x.type())

x =  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
Type :  torch.IntTensor


In [107]:
# 크기와 랭크(차원) 확인하기

print("Size : ", x.size())
print("Shape : ", x.shape)
print("차원(랭크 : ", x.ndimension())

Size :  torch.Size([3, 3])
Shape :  torch.Size([3, 3])
차원(랭크 :  2


In [108]:
# 텐서 모양 바꾸기
# unsqueeze(x, i): tensor x에 i 번째 차원 추가

x0 = torch.unsqueeze(x, 0)
x1 = torch.unsqueeze(x, 1)
x2 = torch.unsqueeze(x, 2)

print("x0.shape :", x0.shape)
print("x1.shape :", x1.shape)
print("x2.shape :", x2.shape)
print("x0 =", x0)
print("x1 =", x1)
print("x2 =", x2)

x0.shape : torch.Size([1, 3, 3])
x1.shape : torch.Size([3, 1, 3])
x2.shape : torch.Size([3, 3, 1])
x0 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32)
x1 = tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]], dtype=torch.int32)
x2 = tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]], dtype=torch.int32)


In [109]:
# squeeze(x): 텐서 x에서 크기가 1인 차원 제거

x3 = torch.squeeze(torch.squeeze(x0))
#x3 = torch.squeeze(x0)
print("x3 =", x3)
print("x3.shape =", x3.shape)

x3 = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)
x3.shape = torch.Size([3, 3])


In [110]:
# x.view([shape]): x를 [shape]의 모양으로 변환

x4 = x.view(9)
print("x4 =", x4)
print("x4.shape =", x4.shape)

x5 = x.view(1,3,3)
print("x5 =", x5)
print("x5.shape =", x5.shape)

x4 = tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
x4.shape = torch.Size([9])
x5 = tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]], dtype=torch.int32)
x5.shape = torch.Size([1, 3, 3])


In [111]:
# 행렬 연산

x = torch.FloatTensor([[1,2], [3,4], [5,6]])
w = torch.randn(1,2, dtype=torch.float)
b = torch.randn(3,1, dtype=torch.float)

print("x * w + b =")
result = torch.mm(x, torch.t(w)) + b # torch.mm(x, w.T) + b
print(result)

x * w + b =
tensor([[2.7185],
        [3.6601],
        [5.5814]])


In [112]:
# 기울기 계산

w = torch.tensor(1.0, requires_grad=True)
a = w * 3
l = a ** 2
l.backward() # 역방향으로 전달하면서 기울기 계산
print('l을 w로 미분한 값은', w.grad)

l을 w로 미분한 값은 tensor(18.)


In [4]:
# Linear Regression
import torch
# x = torch.FloatTensor([[1,2], [3,2], [3,7], [1,1], [1,0]])
# y = torch.FloatTensor([[4], [8], [23], [1], [-2]])

x = torch.FloatTensor([[1], [1], [2],[3]])
y = torch.FloatTensor([[1], [2], [3], [3]])

W = torch.tensor([[1.0]], requires_grad=True)
b = torch.tensor([1.0], requires_grad=True)
lr = 0.1

# print(x)
# W = torch.zeros(2,1)
# b = torch.zeros(1)


for epoch in range(1):
  W.requires_grad_(True)
  b.requires_grad_(True)

  h = torch.mm(x, W) + b
  cost = torch.mean((h - y) ** 2)
  
  cost.backward()
  with torch.no_grad():
    W = W - lr * W.grad
    b = b - lr * b.grad

    if epoch % 100 == 0:
      print( 'epoch: {}, cost: {:.6f}, W: {}, b: {}'.format(epoch,
 cost.item(), W.squeeze(), b))

epoch: 0, cost: 0.500000, W: 0.800000011920929, b: tensor([0.9000])


In [114]:
x_test = torch.tensor([[5,10]], dtype=torch.float)
test_result = torch.mm(x_test, W) + b
print(test_result)

tensor([[35.9998]])


In [115]:
from sklearn.linear_model import LinearRegression

# Scikit-learn

x = [[1,2], [3,2], [3,7], [1,1], [1,0]]
y = [[4], [8], [23], [1], [-2]]

model = LinearRegression()
model.fit(x,y)

# coef_: 기울기 값 (W에 해당), intercept_: y절편 값 (b에 해당)
print(model.coef_, model.intercept_)

print("y 값 예측 :", model.predict([[5,10]]))

[[2. 3.]] [-4.]
y 값 예측 : [[36.]]


In [116]:
##############################################
##### L04.1 Logistic Regression Practice #####
##############################################

In [117]:
import torch

x_train = torch.tensor([[1],[2],[3],[4],[5],[2.5],[3.5],[0],[3.1],[2.7],[2.8],[2.9]], dtype=torch.float)
y_train = torch.tensor([[1],[1],[1],[0],[0],[0],[0],[1],[0],[1],[1],[1]], dtype=torch.float)

W = torch.randn(1, 1)
b = torch.randn(1, 1)

lr = 1.0

for epoch in range(3001):
    W.requires_grad_(True)
    b.requires_grad_(True)

    h = torch.sigmoid(torch.mm(x_train, W) + b)

    cost = torch.mean( -y_train * torch.log(h)
                     -(1 - y_train) * torch.log(1 - h))
    
    cost.backward()

    with torch.no_grad():
        W = W - lr * W.grad
        b = b - lr * b.grad

        if epoch % 100 == 0:
            print( 'epoch: {}, cost: {:.6f}, W: {:.6f}, b: {:.6f}'.format(
 epoch, cost.item(), W.squeeze(), b.squeeze()))

epoch: 0, cost: 0.662105, W: -0.044866, b: 0.509000
epoch: 100, cost: 0.419009, W: -1.470418, b: 4.465821


epoch: 200, cost: 0.398351, W: -1.909160, b: 5.806341
epoch: 300, cost: 0.390655, W: -2.181536, b: 6.631344
epoch: 400, cost: 0.386922, W: -2.372570, b: 7.207379
epoch: 500, cost: 0.384875, W: -2.514600, b: 7.634469
epoch: 600, cost: 0.383669, W: -2.623876, b: 7.962452
epoch: 700, cost: 0.382925, W: -2.709857, b: 8.220172
epoch: 800, cost: 0.382450, W: -2.778574, b: 8.425944
epoch: 900, cost: 0.382141, W: -2.834128, b: 8.592167
epoch: 1000, cost: 0.381936, W: -2.879428, b: 8.727633
epoch: 1100, cost: 0.381798, W: -2.916612, b: 8.838774
epoch: 1200, cost: 0.381704, W: -2.947297, b: 8.930455
epoch: 1300, cost: 0.381639, W: -2.972722, b: 9.006396
epoch: 1400, cost: 0.381595, W: -2.993859, b: 9.069517
epoch: 1500, cost: 0.381564, W: -3.011481, b: 9.122128
epoch: 1600, cost: 0.381542, W: -3.026205, b: 9.166080
epoch: 1700, cost: 0.381527, W: -3.038529, b: 9.202863
epoch: 1800, cost: 0.381516, W: -3.048862, b: 9.233697
epoch: 1900, cost: 0.381509, W: -3.057531, b: 9.259568
epoch: 2000, cost:

In [118]:
# x = [4.5] 혹은 [1.1]일 때, y는 0일까 1일까?

x_test = torch.tensor([[4.5], [1.1]], dtype=torch.float)  
test_result = torch.sigmoid(torch.mm(x_test, W) + b)
print(torch.round(test_result))

tensor([[0.],
        [1.]])


In [119]:
# optimizer 사용해보기

x_train = torch.tensor([[1],[2],[3],[4],[5],[2.5],[3.5],[0],[3.1],[2.7],[2.8],[2.9]], dtype=torch.float)
y_train = torch.tensor([[1],[1],[1],[0],[0],[0],[0],[1],[0],[1],[1],[1]], dtype=torch.float)

W = torch.randn(1, 1, requires_grad=True)
b = torch.randn(1, 1, requires_grad=True)

optimizer = torch.optim.SGD([W,b], lr=1.0)

for epoch in range(3001):
    h = torch.sigmoid(torch.mm(x_train, W) + b)
    cost = torch.mean( -y_train * torch.log(h)
                     -(1 - y_train) * torch.log(1 - h))

    optimizer.zero_grad() # 기울기 초기화
    cost.backward()   # 기울기 계산
    optimizer.step()      # 갱신

    with torch.no_grad():
        if epoch % 100 == 0:
            print( 'epoch: {}, cost: {:.6f}, W: {:.6f}, b: {:.6f}'.format(
 epoch, cost.item(), W.squeeze(), b.squeeze()))


epoch: 0, cost: 0.804141, W: -0.114181, b: 1.361770
epoch: 100, cost: 0.416032, W: -1.519656, b: 4.617093


epoch: 200, cost: 0.397409, W: -1.937220, b: 5.891557
epoch: 300, cost: 0.390229, W: -2.200523, b: 6.688684
epoch: 400, cost: 0.386697, W: -2.386412, b: 7.249043
epoch: 500, cost: 0.384745, W: -2.525119, b: 7.666063
epoch: 600, cost: 0.383590, W: -2.632083, b: 7.987066
epoch: 700, cost: 0.382875, W: -2.716376, b: 8.239701
epoch: 800, cost: 0.382419, W: -2.783822, b: 8.441648
epoch: 900, cost: 0.382120, W: -2.838391, b: 8.604918
epoch: 1000, cost: 0.381922, W: -2.882918, b: 8.738067
epoch: 1100, cost: 0.381788, W: -2.919487, b: 8.847365
epoch: 1200, cost: 0.381697, W: -2.949676, b: 8.937562
epoch: 1300, cost: 0.381635, W: -2.974696, b: 9.012294
epoch: 1400, cost: 0.381592, W: -2.995503, b: 9.074426
epoch: 1500, cost: 0.381562, W: -3.012855, b: 9.126229
epoch: 1600, cost: 0.381541, W: -3.027355, b: 9.169512
epoch: 1700, cost: 0.381526, W: -3.039492, b: 9.205738
epoch: 1800, cost: 0.381516, W: -3.049670, b: 9.236112
epoch: 1900, cost: 0.381508, W: -3.058213, b: 9.261600
epoch: 2000, cost:

In [1]:
import matplotlib.pyplot as plt

W.requires_grad_(False)
b.requires_grad_(False)

with torch.no_grad():
    plt.scatter(x_train, y_train)

    x_tmp = torch.linspace(0, 5, 100).unsqueeze(1)
    y_tmp = torch.sigmoid(torch.mm(x_tmp, W) + b)
    plt.plot(x_tmp, y_tmp, c="#ff0000")
    plt.xlabel("Input (X)")
    plt.ylabel("Probability of 1 (Y)")
    plt.show()

NameError: name 'W' is not defined

In [121]:
# Logistic Regression with sklearn

from sklearn.linear_model import LogisticRegression

x_train = [[1],[2],[3],[4],[5],[2.5],[3.5],[0],[3.1],[2.7],[2.8],[2.9]]
y_train = [1,1,1,0,0,0,0,1,0,1,1,1]

model = LogisticRegression(penalty=None)
model.fit(x_train,  y_train)

print(model.coef_, model.intercept_)

x_test = [[4.5], [1.1]]
test_result = model.predict(x_test)
print(test_result)

[[-3.10385806]] [9.39776831]
[0 1]


In [122]:
#############################################
##### L05.1 Softmax Regression Practice #####
#############################################

In [123]:
import torch

# Softmax Regression

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], 
                             [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], 
                             [0,1,0], [0,1,0], [1,0,0], [1,0,0] ])

W = torch.randn(4, 3, requires_grad=True)
b = torch.randn(1, 3, requires_grad=True)

optimizer = torch.optim.Adam([W, b], lr=0.1)

for epoch in range(3001):
    h = torch.softmax(torch.mm(x_train, W) + b, dim=1)
    cost = -torch.mean(torch.sum(y_train * torch.log(h), dim=1))
    
    # ==
    #h = (torch.mm(x_train, W)+b).softmax(dim=1)
    #cost = -(y_train * torch.log(h)).sum(dim=1).mean()
    
    optimizer.zero_grad() # 기울기 초기화
    cost.backward()   # 기울기 계산
    optimizer.step()      # 갱신

    with torch.no_grad():
        if epoch % 100 == 0:
            print(f"epoch: {epoch}, cost: {cost.item():.6f}")

epoch: 0, cost: 7.334156
epoch: 100, cost: 0.424280


epoch: 200, cost: 0.285709
epoch: 300, cost: 0.202886
epoch: 400, cost: 0.151288
epoch: 500, cost: 0.117249
epoch: 600, cost: 0.093515
epoch: 700, cost: 0.076245
epoch: 800, cost: 0.063268
epoch: 900, cost: 0.053269
epoch: 1000, cost: 0.045405
epoch: 1100, cost: 0.039114
epoch: 1200, cost: 0.034004
epoch: 1300, cost: 0.029800
epoch: 1400, cost: 0.026301
epoch: 1500, cost: 0.023357
epoch: 1600, cost: 0.020859
epoch: 1700, cost: 0.018720
epoch: 1800, cost: 0.016876
epoch: 1900, cost: 0.015274
epoch: 2000, cost: 0.013875
epoch: 2100, cost: 0.012645
epoch: 2200, cost: 0.011558
epoch: 2300, cost: 0.010594
epoch: 2400, cost: 0.009734
epoch: 2500, cost: 0.008964
epoch: 2600, cost: 0.008273
epoch: 2700, cost: 0.007649
epoch: 2800, cost: 0.007086
epoch: 2900, cost: 0.006574
epoch: 3000, cost: 0.006109


In [124]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.tensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]], dtype=torch.float)
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 1.2236e-16, 3.6974e-34],
        [1.3359e-04, 8.3150e-01, 1.6836e-01],
        [4.2444e-30, 9.9820e-11, 1.0000e+00]])
tensor([0, 1, 2])


In [125]:
# 조금 더 깔끔하게 softmax

import torch
import torch.nn.functional as F

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], 
                             [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])

# y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0] ])
# -> 깔끔하게 수정
y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

W = torch.randn(4, 3, requires_grad=True)
b = torch.randn(1, 3, requires_grad=True)

optimizer = torch.optim.Adam([W, b], lr=0.1)

for epoch in range(3001):
    z = torch.mm(x_train, W) + b
    cost = F.cross_entropy(z, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    with torch.no_grad():
        if epoch % 100 == 0:
            print(f"epoch: {epoch}, cost: {cost.item():.6f}")


epoch: 0, cost: 8.376946


epoch: 100, cost: 0.399781
epoch: 200, cost: 0.288080
epoch: 300, cost: 0.211897
epoch: 400, cost: 0.161152
epoch: 500, cost: 0.126590
epoch: 600, cost: 0.102066
epoch: 700, cost: 0.083995
epoch: 800, cost: 0.070266
epoch: 900, cost: 0.059580
epoch: 1000, cost: 0.051095
epoch: 1100, cost: 0.044246
epoch: 1200, cost: 0.038640
epoch: 1300, cost: 0.033994
epoch: 1400, cost: 0.030102
epoch: 1500, cost: 0.026810
epoch: 1600, cost: 0.024002
epoch: 1700, cost: 0.021587
epoch: 1800, cost: 0.019497
epoch: 1900, cost: 0.017675
epoch: 2000, cost: 0.016079
epoch: 2100, cost: 0.014672
epoch: 2200, cost: 0.013426
epoch: 2300, cost: 0.012318
epoch: 2400, cost: 0.011328
epoch: 2500, cost: 0.010441
epoch: 2600, cost: 0.009642
epoch: 2700, cost: 0.008921
epoch: 2800, cost: 0.008269
epoch: 2900, cost: 0.007675
epoch: 3000, cost: 0.007136


In [126]:
import torch
import torch.nn.functional as F
import torch.nn as nn

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], 
                             [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.tensor([2,2,2,1,1,1,0,0], dtype=torch.long)

model = nn.Linear(4, 3)

optimizer = torch.optim.Adam(model.parameters(), lr=1)


for epoch in range(3001):
    #  z = torch.mm(x_train, W) + b
    # -> 수정
    z = model(x_train)
    cost = F.cross_entropy(z, y_train)
    
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    with torch.no_grad():
        if epoch % 100 == 0:
            print(f"epoch: {epoch}, cost: {cost.item():.6f}")

epoch: 0, cost: 3.131099
epoch: 100, cost: 0.099255
epoch: 200, cost: 0.051740
epoch: 300, cost: 0.031736
epoch: 400, cost: 0.022099
epoch: 500, cost: 0.016361
epoch: 600, cost: 0.012632
epoch: 700, cost: 0.010065
epoch: 800, cost: 0.008219
epoch: 900, cost: 0.006843
epoch: 1000, cost: 0.005789
epoch: 1100, cost: 0.004961
epoch: 1200, cost: 0.004298
epoch: 1300, cost: 0.003759
epoch: 1400, cost: 0.003313
epoch: 1500, cost: 0.002941
epoch: 1600, cost: 0.002626
epoch: 1700, cost: 0.002357
epoch: 1800, cost: 0.002126
epoch: 1900, cost: 0.001925
epoch: 2000, cost: 0.001750
epoch: 2100, cost: 0.001596
epoch: 2200, cost: 0.001460
epoch: 2300, cost: 0.001340
epoch: 2400, cost: 0.001232
epoch: 2500, cost: 0.001136
epoch: 2600, cost: 0.001049
epoch: 2700, cost: 0.000971
epoch: 2800, cost: 0.000900
epoch: 2900, cost: 0.000836
epoch: 3000, cost: 0.000777


In [127]:
# softmax regression in sklearn

import numpy as np
from sklearn.linear_model import LogisticRegression

x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5],
                   [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = np.array([ 2, 2, 2, 1, 1, 1, 0, 0 ])

logistic = LogisticRegression() # 모델 생성
logistic.fit(x_train, y_train) # 학습

x_test = np.array([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
pred = logistic.predict(x_test) # test case (값 예측)
print(pred) # 출력

[0 2 2]
