In [1]:
import torch

x = torch.tensor([[1, 2], [3, 4], [5, 6]])
y = torch.FloatTensor([[[1, 2], [3, 4]], [[1, 2], [3, 4]], [[1, 2], [3, 4]]])

print(x)
print(x.type)
print(x.size())
print(x.shape)
print(x.ndimension())

print(y)
print(y.shape)



tensor([[1, 2],
        [3, 4],
        [5, 6]])
<built-in method type of Tensor object at 0x0000029B67670590>
torch.Size([3, 2])
torch.Size([3, 2])
2
tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])
torch.Size([3, 2, 2])


In [2]:
y = torch.FloatTensor([[[1, 2], [3, 4]], [[1, 2], [3, 4]], [[1, 2], [3, 4]]])



print(y.shape)
print(y)

y.unsqueeze(0) # 0번째 위치에 새로운 차원을 추가, 프린트해보면 가장 바깥쪽에 대괄호 하나 더 늘어나있음

y0 = y.unsqueeze(1)
print(y0)

torch.Size([3, 2, 2])
tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])
tensor([[[[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]]]])


In [3]:
x0 = x.unsqueeze(0) # [3, 2, 2] --> [1, 3, 2, 2]
x1 = x.unsqueeze(1) # [3, 2, 2] --> [3, 1, 2, 2]
x2 = x.unsqueeze(2) # [3, 2, 2] --> [3, 2, 1, 2]
#x3 = x.unsqueeze(3) # [3, 2, 2] --> [3, 2, 2, 1]

In [4]:
x2.shape
print(x2)
x2.squeeze(0)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])


tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [5]:
print(x)

x.view(8)

tensor([[1, 2],
        [3, 4],
        [5, 6]])


RuntimeError: shape '[8]' is invalid for input of size 6

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4], [5, 6]])
w = torch.rand(1,2, dtype=torch.float)
b = torch.rand(3,1, dtype=torch.float)

#torch.mm(x, w.T) # 행렬곱셈을 하기 위해 w를 전치행렬로 바꾸어준다. or t(w) 해도 됨.

print(x @ w.T + b)

print(x)
print(w)
print(b)

tensor([[1.4172],
        [3.2029],
        [4.2452]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[0.1693, 0.5228]])
tensor([[0.2022],
        [0.6037],
        [0.2618]])


In [ ]:
w = torch.tensor(1.0, requires_grad=True)
a = w*3
l = a**2
l.backward()
print(w.grad)

tensor(18.)


In [6]:
x_train=torch.FloatTensor([[1,2],[3,2],[3,7],[1,1],[1,0]])
y_train=torch.FloatTensor([[4],[8],[23],[1],[-2]])

w = torch.randn(2, 1)
b = torch.randn(1)

lr = 0.01

In [7]:
for epoch in range(3001):
    w.requires_grad_(True)
    b.requires_grad_(True)
    
    h = x_train @ w + b
    cost = (h - y_train ** 2).mean() # 평균
    cost.backward()
    
    with torch.no_grad():
        w = w - lr * w.grad
        b = b - lr * b.grad
        
        if epoch % 100 == 0:
            print(epoch, cost.item(), w.squeeze(), b)

    

0 -118.6669692993164 tensor([-0.4138,  1.5517]) tensor([1.0537])
100 -128.66697692871094 tensor([-2.2138, -0.8483]) tensor([0.0537])
200 -138.6669464111328 tensor([-4.0137, -3.2483]) tensor([-0.9463])
300 -148.66697692871094 tensor([-5.8138, -5.6483]) tensor([-1.9463])
400 -158.6670684814453 tensor([-7.6138, -8.0483]) tensor([-2.9463])
500 -168.6670379638672 tensor([ -9.4137, -10.4484]) tensor([-3.9463])
600 -178.66705322265625 tensor([-11.2137, -12.8484]) tensor([-4.9463])
700 -188.6670379638672 tensor([-13.0137, -15.2484]) tensor([-5.9463])
800 -198.66705322265625 tensor([-14.8136, -17.6484]) tensor([-6.9463])
900 -208.6670379638672 tensor([-16.6136, -20.0484]) tensor([-7.9464])
1000 -218.6670379638672 tensor([-18.4136, -22.4484]) tensor([-8.9464])
1100 -228.6670684814453 tensor([-20.2135, -24.8485]) tensor([-9.9464])
1200 -238.6670379638672 tensor([-22.0135, -27.2485]) tensor([-10.9464])
1300 -248.6670379638672 tensor([-23.8135, -29.6485]) tensor([-11.9464])
1400 -258.66705322265625

In [9]:
from sklearn.linear_model import LinearRegression